merge_method: task_arithmetic_neg
base_model: ./local_roberta_models/roberta-base
models_to_merge: auto
scaling: 0.7
models_name: auto
exclude_param: auto
model_loader: auto
dtype: auto
negation:
  - sst2